### PR TITLE
Separation of EJBCA from x509-identity-mgmt and volume sharing

### PR DESCRIPTION
**Pull request by thiagodpf**
* **Please check if the PR fulfills these requirements**
  * [ ] Tests for the changes have been added (for bug fixes / features)
  * [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

feature

* **What is the current behavior?** (You can also link to an open issue here)

The x509-identity-mgmt container also performed the EJBCA internally.

* **What is the new behavior (if this is a feature change)?**

EJBCA has its own container again, but now it shares a volume with x509-identity-mgmt.
The volume is used to store the .12 file that gives x509-identity-mgmt access to the EJBCA API.
In the future, it would be interesting to keep .p12 in a secret that only the two Pods had access to. A kind of secret in the form of a mount point.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

dojot/dojot#1964
dojot/docker-compose#220

* **Other information**:

This PR does not need to be approved, but it serves as a reference to know what has been changed in the Pods.

### CODE REVIEW

**Comment by mprevide** [comment]
Please, don't merge this yet! :)
I could create the branch because there is another PR open to dev

**Review by LeonardoMariano — COMMENTED** [review]
I think it is necessary to add these variables to docs/vars.md
`dojot_x509_ejbca_persistent_volumes`
`dojot_x509_ejbca_volume_size`

**Comment by jonaphael** [comment]
I left some comments about the behavior I've found testing this PR
This error is showing more often when bringing up the enviroment
image

x509 and ejbca volumes now are required, I had to modified the pods affinity and sets the variables to enable the volumes
I think it could be a little more easier (the default variables) to setup, for new users.

Everything works fine.
I suggest you to add a note about how to solve this error when its happens.
Error: self signed certificate in certificate chain

**Comment by thiagodpf** [comment]
a new PR will be created in the new ansible sctructure

**Comment by thiagodpf** [comment]
https://github.com/dojot/ansible-dojot/pull/114

**Pull request closed without merging**
